name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Getting Started
      id: getting-started
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Getting Started
        setup-command: pip install pytest
        command: pytest Getting\ Started/test_hello_world.py
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        GETTING-STARTED_RESULTS: "${{steps.getting-started.outputs.result}}"
      with:
        runners: getting-started
